### ISSUE TITLE
没效果

### ISSUE THREAD

**Issue by tiefeiniu** [coder-pig/CPWechatXposed#6]
手机已root和安装Xposed框架，运行这个模块安装时，那些功能再微信上都不起作用，我用框架里面的模块时可以的，打开的时候也提示说Xposed模块已激活
微信版本是7.04
手机系统是7.1

**Comment by coder-pig** [comment]
不会吧，我也在用啊，是不是插件冲突了？

**Comment by coder-pig** [comment]
> 手机已root和安装Xposed框架，运行这个模块安装时，那些功能再微信上都不起作用，我用框架里面的模块时可以的，打开的时候也提示说Xposed模块已激活
> 微信版本是7.04
> 手机系统是7.1

我的插件打开后有没有谈那个插件未启用的Toast？

**Comment by tiefeiniu** [comment]
> > 手机已root和安装Xposed框架，运行这个模块安装时，那些功能再微信上都不起作用，我用框架里面的模块时可以的，打开的时候也提示说Xposed模块已激活
> > 微信版本是7.04
> > 手机系统是7.1
> 
> 我的插件打开后有没有谈那个插件未启用的Toast？

弹出来的，我自己在代码里面加了else，是已激活了， if (!isModuleActive()) {
            shortToast("Xposed模块未激活!")
        }else{
            shortToast("Xposed模块已激活!")
        }

**Comment by coder-pig** [comment]
自己编译的apk吗？我猜测是不是installrun开关没有关...

**Comment by coder-pig** [comment]
> > > 手机已root和安装Xposed框架，运行这个模块安装时，那些功能再微信上都不起作用，我用框架里面的模块时可以的，打开的时候也提示说Xposed模块已激活
> > > 微信版本是7.04
> > > 手机系统是7.1
> > 
> > 
> > 我的插件打开后有没有谈那个插件未启用的Toast？
> 
> 弹出来的，我自己在代码里面加了else，是已激活了， if (!isModuleActive()) {
> shortToast("Xposed模块未激活!")
> }else{
> shortToast("Xposed模块已激活!")
> }

自己编译的apk吗？我猜测是不是installrun开关没有关...

**Comment by tiefeiniu** [comment]
> > > > 手机已root和安装Xposed框架，运行这个模块安装时，那些功能再微信上都不起作用，我用框架里面的模块时可以的，打开的时候也提示说Xposed模块已激活
> > > > 微信版本是7.04
> > > > 手机系统是7.1
> > > 
> > > 
> > > 我的插件打开后有没有谈那个插件未启用的Toast？
> > 
> > 
> > 弹出来的，我自己在代码里面加了else，是已激活了， if (!isModuleActive()) {
> > shortToast("Xposed模块未激活!")
> > }else{
> > shortToast("Xposed模块已激活!")
> > }
> 
> 自己编译的apk吗？我猜测是不是installrun开关没有关...

是自己编译的，installrun也是关了呀

**Comment by tiefeiniu** [comment]
- 

- 

- [ ] 

> > > > > 手机已root和安装Xposed框架，运行这个模块安装时，那些功能再微信上都不起作用，我用框架里面的模块时可以的，打开的时候也提示说Xposed模块已激活
> > > > > 微信版本是7.04
> > > > > 手机系统是7.1
> > > > 
> > > > 
> > > > 我的插件打开后有没有谈那个插件未启用的Toast？
> > > 
> > > 
> > > 弹出来的，我自己在代码里面加了else，是已激活了， if (!isModuleActive()) {
> > > shortToast("Xposed模块未激活!")
> > > }else{
> > > shortToast("Xposed模块已激活!")
> > > }
> > 
> > 
> > 自己编译的apk吗？我猜测是不是installrun开关没有关...
> 
> 是自己编译的，installrun也是关了呀

是需要打包成正式包吗？直接编译安装不行？

**Comment by coder-pig** [comment]
> > > > > 手机已root和安装Xposed框架，运行这个模块安装时，那些功能再微信上都不起作用，我用框架里面的模块时可以的，打开的时候也提示说Xposed模块已激活
> > > > > 微信版本是7.04
> > > > > 手机系统是7.1
> > > > 
> > > > 
> > > > 我的插件打开后有没有谈那个插件未启用的Toast？
> > > 
> > > 
> > > 弹出来的，我自己在代码里面加了else，是已激活了， if (!isModuleActive()) {
> > > shortToast("Xposed模块未激活!")
> > > }else{
> > > shortToast("Xposed模块已激活!")
> > > }
> > 
> > 
> > 自己编译的apk吗？我猜测是不是installrun开关没有关...
> 
> 是自己编译的，installrun也是关了呀

我刚把代码编译了生成apk，然后安装了最新的微信，插件是生效的，你是改动了代码吧？

**Comment by coder-pig** [comment]
😶我的几个小伙伴也在用啊，都没问题...

**Comment by tiefeiniu** [comment]
> > > > > > 手机已root和安装Xposed框架，运行这个模块安装时，那些功能再微信上都不起作用，我用框架里面的模块时可以的，打开的时候也提示说Xposed模块已激活
> > > > > > 微信版本是7.04
> > > > > > 手机系统是7.1
> > > > > 
> > > > > 
> > > > > 我的插件打开后有没有谈那个插件未启用的Toast？
> > > > 
> > > > 
> > > > 弹出来的，我自己在代码里面加了else，是已激活了， if (!isModuleActive()) {
> > > > shortToast("Xposed模块未激活!")
> > > > }else{
> > > > shortToast("Xposed模块已激活!")
> > > > }
> > > 
> > > 
> > > 自己编译的apk吗？我猜测是不是installrun开关没有关...
> > 
> > 
> > 是自己编译的，installrun也是关了呀
> 
> 我刚把代码编译了生成apk，然后安装了最新的微信，插件是生效的，你是改动了代码吧？

代码没改呀，就加了那个提示，打开的时候是提示说已激活，但是上面的功能微信上没反应
